spring:
  application:
    name: hello-service
  config:
    import: "optional:configserver:"
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: true
        service-id: cloud-config-server

server:
  port: 8101
management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health