version: '3.7'
networks:
  msa-env:
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "9411:9411"
    networks:
      - msa-env
