spring:
  application:
    name: cloud-config-server
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
  security:
    user:
      name: user
      password: 1234
  zipkin:
    base-url: http://jaeger-collector/
    discovery-client-enabled: true

encrypt:
  key: 1234567890
